apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: netbox-sc
  namespace: netbox
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: RG-Netbox-001
  storageAccount: netboxstorage001
  server: netboxstorage001.file.core.windows.net 
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload