apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-pvc
  namespace: netbox
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: netbox-pvc
  resources:
    requests:
      storage: 100Gi