apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
  namespace: psql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: psql-pvc
  resources:
    requests:
      storage: 100Gi